# Site settings
title: Introduction to Linux
email: rrockers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Class notes, stuff from whiteboards, and braindumps I needed to put somewhere.
baseurl: "/nt1430" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rrockers
github_username:  brockers
permalink: none

# Build settings
# markdown: kramdown
markdown: redcarpet
