#!/bin/bash

# This is the only line you should change to 
# execute my totally awesome program.
NAMEOFPERSON="Jimmy"
ROTATION=$1

# Real code goes here  DONT TOUCH
# for I in {1..5}; do
#   echo "Hello $HELLONAME"
# done

echo "$NAMEOFPERSON says hi!"

echo "We are going to process our flags."

for i in $(ls flags/); do
  echo "Name of our file is $i"
  convert flags/$i -rotate $ROTATION flags/"new$i"
done